(() => {
  const accessTeam=document.body.dataset.accessTeam;
  const $=id=>document.getElementById(id);
  let state=null,view="attack";
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  async function json(url,options={}){const r=await fetch(url,{cache:"no-store",...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed.");return d;}
  async function session(){const d=await json("/api/bingo/team-session");const info=d.teams?.[accessTeam];$("pageTeamName").textContent=info?.name|| (accessTeam==="team1"?"Team 1":"Team 2");if(d.team===accessTeam){await loadBoard();}else{showLogin();}}
  function showLogin(message=""){$("loginPanel").classList.remove("hidden");$("boardPanel").classList.add("hidden");$("logoutTeamBtn").classList.add("hidden");$("loginError").textContent=message;}
  async function loadBoard(){try{state=await json("/api/bingo/team-board");$("loginPanel").classList.add("hidden");$("boardPanel").classList.remove("hidden");$("logoutTeamBtn").classList.remove("hidden");$("pageTeamName").textContent=state.ownTeam.name;$("ownName").textContent=state.ownTeam.name;$("opponentName").textContent=state.opponent.name;$("phaseName").textContent=state.phase;render();}catch(e){showLogin(e.message);}}
  function progress(tile){return tile.teamProgress?.[state.viewerTeam]||{completedQuantity:0,status:"open"};}
  function attackAt(index,kind){return state.attacks.find(a=>kind==="out"?a.attackingTeam===state.viewerTeam&&a.targetIndex===index:a.defendingTeam===state.viewerTeam&&a.targetIndex===index);}
  function render(){const attack=view==="attack";$("attackViewBtn").classList.toggle("active",attack);$("watersViewBtn").classList.toggle("active",!attack);$("boardTitle").textContent=attack?`Attacking ${state.opponent.name}'s Waters`:`${state.ownTeam.name}'s Waters`;const board=$("teamBoard");board.innerHTML=state.tiles.map((tile,index)=>{const a=attackAt(index,attack?"out":"in"),p=progress(tile),ship=!attack?state.ownTeam.ships.find(s=>s.cells.includes(index)):null,complete=Number(p.completedQuantity)>=Number(tile.quantity);const classes=["team-tile",a?.result||"",ship?"ship":"",complete?"complete":""].filter(Boolean).join(" ");return`<button class="${classes}" data-index="${index}" type="button" ${attack&&tile.name&&state.phase==="active"?"":"disabled"} title="${esc(tile.name||"Empty")}">${tile.quantity>1?`<small>x${tile.quantity}</small>`:""}${tile.image?`<img src="${esc(tile.image)}" alt="">`:""}<span>${esc(tile.name||"Empty")}</span>${a?`<b class="marker">${a.result==="hit"?"HIT":"MISS"}</b>`:""}${ship?`<b class="marker">${esc(ship.name.charAt(0))}</b>`:""}</button>`;}).join("");if(attack)board.querySelectorAll("button:not([disabled])").forEach(b=>b.addEventListener("click",()=>openProof(Number(b.dataset.index))));}
  function openProof(index){const tile=state.tiles[index];$("proofTileIndex").value=String(index);$("proofTitle").textContent=`Submit Proof — ${tile.name}`;$("proofQuantity").max=String(Math.max(1,Number(tile.quantity)-Number(progress(tile).completedQuantity||0)));$("proofQuantity").value="1";$("proofError").textContent="";$("proofDialog").showModal();}
  $("teamLoginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginError").textContent="";try{await json("/api/bingo/team-login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({team:accessTeam,password:$("teamPassword").value})});$("teamPassword").value="";await loadBoard();}catch(err){$("loginError").textContent=err.message;}});
  $("logoutTeamBtn").addEventListener("click",async()=>{await fetch("/api/bingo/team-session",{method:"DELETE"});showLogin();});
  $("attackViewBtn").addEventListener("click",()=>{view="attack";render();});$("watersViewBtn").addEventListener("click",()=>{view="waters";render();});$("cancelProofBtn").addEventListener("click",()=>$("proofDialog").close());
  $("proofForm").addEventListener("submit",async e=>{e.preventDefault();$("proofError").textContent="";try{await json("/api/bingo/team-proof",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tileIndex:Number($("proofTileIndex").value),player:$("proofPlayer").value,url:$("proofUrl").value,quantity:Number($("proofQuantity").value),note:$("proofNote").value})});$("proofDialog").close();$("proofForm").reset();await loadBoard();alert("Proof submitted for staff review.");}catch(err){$("proofError").textContent=err.message;}});
  session().catch(e=>showLogin(e.message));
})();
