let gamesState=null; let activeTab="overview"; const $=id=>document.getElementById(id);
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function fmtDate(v){if(!v)return"TBD";const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString(undefined,{weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}):v;}
function currentWeek(){const now=Date.now();return gamesState?.weeks?.find(w=>{const a=new Date(w.startDate||0).getTime(),b=new Date(w.endDate||8640000000000000).getTime();return now>=a&&now<=b;})||gamesState?.weeks?.find(w=>(w.challenges||[]).some(c=>c.status==="active"))||gamesState?.weeks?.[0];}
function standings(){return [...(gamesState?.teams||[])].sort((a,b)=>(Number(b.points)||0)-(Number(a.points)||0));}
function standingHtml(){return `<div class="games-standings">${standings().map((t,i)=>`<div class="games-standing"><span class="rank">${i+1}</span><div><strong>${esc(t.name)}</strong><div class="games-muted">${(t.members||[]).length} members</div></div><strong>${Number(t.points)||0} pts</strong></div>`).join("")||"No teams configured yet."}</div>`;}
function renderOverview(){const week=currentWeek();return `<div class="games-grid"><article class="games-card"><p class="eyebrow">Standings</p><h2>Leaderboard</h2>${standingHtml()}</article><article class="games-card"><p class="eyebrow">Current round</p><h2>${esc(week?.name||"Coming Soon")}</h2><div class="games-kpi">${week?.challenges?.length||0}</div><p class="games-muted">scheduled challenges</p>${gamesState.myTeam?`<p>Your team: <strong>${esc(gamesState.myTeam.name)}</strong></p>`:`<p class="games-muted">Sign in to see team-specific challenge access.</p>`}${gamesState.signupOpen?`<a class="games-btn" href="/ironkin-games-signup.html">Sign Up for Ironkin Games</a>`:""}</article><article class="games-card full"><p class="eyebrow">Format</p><h2>How it works</h2><p>Main Challenges use private timed reveals. Teams compete in their own scheduled window, submit a VOD/proof link, and results remain hidden from other teams until staff unlock them. Side Challenges can stay open across the full challenge window.</p></article></div>`;}
function challengeHtml(week,c){const s=c.session;const running=s?.startedAt&&s.status==="running";const revealed=Boolean(c.objective||c.instructions);return `<article class="games-card challenge-card"><p class="eyebrow">${esc((c.kind||"main").toUpperCase())}</p><h2>${esc(c.name)}</h2><p>${esc(c.summary|| (c.kind==="main"&&!revealed?"Challenge details are hidden until your team starts.":""))}</p><div class="challenge-meta"><span>${Number(c.durationMinutes)||0} min</span><span>${esc(c.participants||"Team-selected")}</span><span>${c.proofRequired===false?"Proof optional":"VOD / proof required"}</span></div>${revealed?`<div class="games-reveal"><strong>Objective</strong><p>${esc(c.objective||c.instructions)}</p>${(c.rules||[]).length?`<ul>${c.rules.map(r=>`<li>${esc(r)}</li>`).join("")}</ul>`:""}</div>`:""}${running?`<div class="games-timer" data-ends="${esc(s.endsAt)}">--:--</div>`:""}<div class="challenge-actions">${c.kind==="main"&&!s?.startedAt&&gamesState.myTeam?`${s?.scheduledAt?`<span class="games-pill">Booked: ${fmtDate(s.scheduledAt)}</span>`:`<input type="datetime-local" data-book-time="${esc(week.id)}|${esc(c.id)}"><button class="games-btn secondary" data-book="${esc(week.id)}|${esc(c.id)}">Book Slot</button>`}<button class="games-btn" data-start="${esc(week.id)}|${esc(c.id)}" ${c.isOpen===false||!s?.scheduledAt?"disabled":""}>Start Challenge</button>`:""}${s?.startedAt?`<span class="games-pill">Started ${fmtDate(s.startedAt)}</span>`:""}</div>${(revealed||c.kind==="side")&&gamesState.myTeam?submissionForm(week,c):""}</article>`;}
function submissionForm(w,c){return `<form class="games-form" data-submit-form="${esc(w.id)}|${esc(c.id)}"><input name="score" placeholder="Score / time / result (example: 18.4M GP)" maxlength="120"><input name="proofUrl" type="url" placeholder="VOD or proof link"><textarea name="notes" rows="3" placeholder="Notes for staff (optional)"></textarea><button class="games-btn secondary" type="submit">Submit Result</button></form>`;}
function renderWeek(){const w=currentWeek();if(!w)return`<div class="games-card full">No week has been configured yet.</div>`;return `<div class="games-grid"><article class="games-card full"><p class="eyebrow">Current week</p><h2>${esc(w.name)}</h2><p>${fmtDate(w.startDate)} - ${fmtDate(w.endDate)}</p></article>${(w.challenges||[]).map(c=>challengeHtml(w,c)).join("")}</div>`;}
function renderTeams(){return `<div class="games-grid">${standings().map(t=>`<article class="games-card"><p class="eyebrow">${Number(t.points)||0} POINTS</p><h2>${esc(t.name)}</h2><div class="games-team-members">${(t.members||[]).map(m=>`<span class="games-pill">${esc(m.name||m.rsn||m.discordId||"Member")}</span>`).join("")||`<span class="games-muted">Roster TBD</span>`}</div></article>`).join("")}</div>`;}
function renderSchedule(){const rows=[];(gamesState.weeks||[]).forEach(w=>(w.challenges||[]).filter(c=>c.kind==="main").forEach(c=>rows.push({w,c})));return `<div class="games-card full"><h2>Challenge Schedule</h2>${rows.map(({w,c})=>`<div class="schedule-row"><strong>${esc(w.name)} · ${esc(c.name)}</strong><span>${fmtDate(c.opensAt)}</span><span>${fmtDate(c.closesAt)}</span></div>`).join("")||"Schedule coming soon."}</div>`;}
function renderResults(){const subs=gamesState.submissions||[];return `<div class="games-grid"><article class="games-card full"><p class="eyebrow">Official scoring</p><h2>${gamesState.resultsUnlocked?"Results":"Results Locked"}</h2>${gamesState.resultsUnlocked?standingHtml():`<p>Individual team results remain hidden until staff unlocks them, protecting later time slots from score and strategy information.</p>`}</article>${subs.length?`<article class="games-card full"><h3>Submitted Results</h3>${subs.map(s=>`<div class="result-row"><span>${esc((gamesState.teams.find(t=>t.id===s.teamId)||{}).name||s.teamId)}</span><strong>${esc(s.score||"Pending")}</strong><span>${esc(s.status)}</span></div>`).join("")}</article>`:""}</div>`;}
function renderRules(){return `<div class="games-grid"><article class="games-card full"><h2>Competition Integrity</h2><ol>${(gamesState.rules||[]).map(r=>`<li>${esc(r)}</li>`).join("")}</ol><p><strong>Main Challenge:</strong> ${gamesState.scoring?.main?.join(" / ")||"100 / 75 / 55 / 40"} points by placement.</p><p><strong>Side Challenge:</strong> ${gamesState.scoring?.side?.join(" / ")||"30 / 20 / 15 / 10"} points by placement.</p></article></div>`;}
function render(){if(!gamesState)return;$("gamesTitle").textContent=gamesState.title||"Ironkin Games";$("gamesSubtitle").textContent=gamesState.subtitle||"";const signupTab=$("gamesSignupTab");if(signupTab)signupTab.hidden=!gamesState.signupOpen;const f={overview:renderOverview,week:renderWeek,teams:renderTeams,schedule:renderSchedule,results:renderResults,rules:renderRules}[activeTab]||renderOverview;$("gamesContent").innerHTML=f();bind();tick();}
function bind(){document.querySelectorAll("[data-book]").forEach(b=>b.onclick=async()=>{const key=b.dataset.book,input=document.querySelector(`[data-book-time="${key}"]`);if(!input?.value){alert("Choose your team start time first.");return;}const [weekId,challengeId]=key.split("|");const r=await fetch("/api/ironkin-games/book",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({weekId,challengeId,scheduledAt:new Date(input.value).toISOString()})});const d=await r.json();if(!r.ok){alert(d.error||"Could not book slot.");return;}await load();});document.querySelectorAll("[data-start]").forEach(b=>b.onclick=async()=>{if(!confirm("Start this challenge now? The timer cannot be paused or restarted."))return;const [weekId,challengeId]=b.dataset.start.split("|");b.disabled=true;const r=await fetch("/api/ironkin-games/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({weekId,challengeId})});const d=await r.json();if(!r.ok){alert(d.error||"Could not start challenge.");b.disabled=false;return;}await load();});document.querySelectorAll("[data-submit-form]").forEach(f=>f.onsubmit=async e=>{e.preventDefault();const [weekId,challengeId]=f.dataset.submitForm.split("|");const fd=new FormData(f);const r=await fetch("/api/ironkin-games/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({weekId,challengeId,score:fd.get("score"),proofUrl:fd.get("proofUrl"),notes:fd.get("notes")})});const d=await r.json();alert(r.ok?"Result submitted for staff review.":(d.error||"Submission failed."));if(r.ok)await load();});}
function tick(){document.querySelectorAll("[data-ends]").forEach(el=>{const remain=Math.max(0,new Date(el.dataset.ends).getTime()-Date.now()),s=Math.floor(remain/1000),m=Math.floor(s/60),sec=s%60;el.textContent=`${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`;});}
async function load(){try{const r=await fetch("/api/ironkin-games/state",{cache:"no-store"});gamesState=await r.json();if(!r.ok)throw new Error(gamesState.error||"Could not load Games.");$("gamesStatus").textContent=gamesState.enabled?"":"Ironkin Games is currently hidden by staff.";render();}catch(e){$("gamesStatus").textContent=e.message;}}
document.querySelectorAll("[data-games-tab]").forEach(b=>b.onclick=()=>{activeTab=b.dataset.gamesTab;document.querySelectorAll("[data-games-tab]").forEach(x=>x.classList.toggle("is-active",x===b));render();});load();setInterval(tick,1000);
