-- Ironkin event/plugin shared tables
-- Run this once in the SAME Supabase project used by the Ironkin Discord bot.
-- Safe for both a fresh setup and upgrading the first event-tracking schema.

create table if not exists public.ironkin_event_items (
  id bigint generated by default as identity primary key,
  website_event_id text not null,
  item_id integer not null check (item_id > 0),
  item_name text not null,
  image_url text not null default '',
  wiki_url text not null default '',
  reward_embers integer not null default 0 check (reward_embers >= 0),
  tracking_rule text not null default 'repeatable' check (tracking_rule in ('repeatable','once_per_player','once_per_event')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (website_event_id, item_id)
);

-- Upgrade path if the table was created before duplicate-rule support.
alter table public.ironkin_event_items add column if not exists tracking_rule text not null default 'repeatable';
do $$ begin
  alter table public.ironkin_event_items add constraint ironkin_event_items_tracking_rule_check
    check (tracking_rule in ('repeatable','once_per_player','once_per_event'));
exception when duplicate_object then null; end $$;

create index if not exists ironkin_event_items_event_idx
  on public.ironkin_event_items (website_event_id);

create table if not exists public.ironkin_event_submissions (
  id uuid primary key,
  plugin_event_id text not null,
  website_event_id text not null,
  event_type text not null default '',
  event_name text not null default '',
  player_name text not null,
  discord_id text not null default '',
  player_key text not null default '',
  item_id integer not null check (item_id > 0),
  item_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  tracking_rule text not null default 'repeatable' check (tracking_rule in ('repeatable','once_per_player','once_per_event')),
  client_submission_key text not null default '',
  source text not null default 'runelite',
  status text not null default 'pending' check (status in ('pending','processing','approved','rejected','failed')),
  proof_url text not null default '',
  client_timestamp timestamptz,
  discord_message_id text not null default '',
  discord_channel_id text not null default '',
  processed_at timestamptz,
  processed_by text not null default '',
  claimed_at timestamptz,
  error_message text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Upgrade path if the table was created before duplicate-rule support.
alter table public.ironkin_event_submissions add column if not exists player_key text not null default '';
alter table public.ironkin_event_submissions add column if not exists tracking_rule text not null default 'repeatable';
alter table public.ironkin_event_submissions add column if not exists client_submission_key text not null default '';
do $$ begin
  alter table public.ironkin_event_submissions add constraint ironkin_event_submissions_tracking_rule_check
    check (tracking_rule in ('repeatable','once_per_player','once_per_event'));
exception when duplicate_object then null; end $$;

create index if not exists ironkin_event_submissions_pending_idx
  on public.ironkin_event_submissions (status, created_at);
create index if not exists ironkin_event_submissions_event_idx
  on public.ironkin_event_submissions (plugin_event_id, created_at desc);
create index if not exists ironkin_event_submissions_discord_idx
  on public.ironkin_event_submissions (discord_id, created_at desc);

-- Network/client retry protection: the same loot event should never create two Discord posts.
create unique index if not exists ironkin_event_submissions_client_key_uq
  on public.ironkin_event_submissions (client_submission_key)
  where client_submission_key <> '';

-- Business duplicate rules. Rejected submissions do not reserve the item, so a corrected proof may be submitted later.
create unique index if not exists ironkin_event_submissions_once_event_uq
  on public.ironkin_event_submissions (plugin_event_id, item_id)
  where tracking_rule = 'once_per_event' and status <> 'rejected';

create unique index if not exists ironkin_event_submissions_once_player_uq
  on public.ironkin_event_submissions (plugin_event_id, item_id, player_key)
  where tracking_rule = 'once_per_player' and status <> 'rejected';

-- These tables are intended for trusted server-side access only.
alter table public.ironkin_event_items enable row level security;
alter table public.ironkin_event_submissions enable row level security;
-- No anon/authenticated policies are intentionally created.
