-- Ironkin event/plugin shared tables
-- Run this once in the SAME Supabase project used by the Ironkin Discord bot.

create table if not exists public.ironkin_event_items (
  id bigint generated by default as identity primary key,
  website_event_id text not null,
  item_id integer not null check (item_id > 0),
  item_name text not null,
  image_url text not null default '',
  wiki_url text not null default '',
  reward_embers integer not null default 0 check (reward_embers >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (website_event_id, item_id)
);

create index if not exists ironkin_event_items_event_idx
  on public.ironkin_event_items (website_event_id);

create table if not exists public.ironkin_event_submissions (
  id uuid primary key,
  plugin_event_id text not null,
  website_event_id text not null,
  event_type text not null default '',
  event_name text not null default '',
  player_name text not null,
  discord_id text not null default '',
  item_id integer not null check (item_id > 0),
  item_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  source text not null default 'runelite',
  status text not null default 'pending' check (status in ('pending','processing','approved','rejected','failed')),
  proof_url text not null default '',
  client_timestamp timestamptz,
  discord_message_id text not null default '',
  discord_channel_id text not null default '',
  processed_at timestamptz,
  processed_by text not null default '',
  claimed_at timestamptz,
  error_message text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ironkin_event_submissions_pending_idx
  on public.ironkin_event_submissions (status, created_at);

create index if not exists ironkin_event_submissions_event_idx
  on public.ironkin_event_submissions (plugin_event_id, created_at desc);

create index if not exists ironkin_event_submissions_discord_idx
  on public.ironkin_event_submissions (discord_id, created_at desc);

-- These tables are intended for trusted server-side access only.
-- The Cloudflare Pages Functions and Discord bot use server-side Supabase secret/service-role credentials.
alter table public.ironkin_event_items enable row level security;
alter table public.ironkin_event_submissions enable row level security;

-- No anon/authenticated policies are intentionally created.
-- service_role / Supabase secret-key backend access bypasses RLS.
