const ACCESS_COOKIE = "ironkin_bingo_team";
const ACCESS_TTL_SECONDS = 60 * 60 * 24 * 14;
const ACCESS_KEY = "bingo:team-access:v1";
const LOGIN_WINDOW_SECONDS = 15 * 60;
const LOGIN_MAX_ATTEMPTS = 8;
const PBKDF2_ITERATIONS = 100000;
const PBKDF2_MAX_ITERATIONS = 100000;
function clamp(value,max=120){return String(value||"").trim().slice(0,max)}
function getCookie(request,name){const cookie=request.headers.get("Cookie")||"";const match=cookie.match(new RegExp(`(?:^|;\\s*)${name}=([^;]+)`));return match?decodeURIComponent(match[1]):""}
function toBase64Url(buffer){let binary="";for(const byte of new Uint8Array(buffer))binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function hmac(payload,secret){if(!secret)throw new Error("SESSION_SECRET is not configured.");const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return toBase64Url(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(payload)))}
function constantTimeEqual(a,b){if(!a||!b||a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i+=1)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
async function hashPassword(password,salt,iterations=PBKDF2_ITERATIONS){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(String(password)),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:new TextEncoder().encode(salt),iterations,hash:"SHA-256"},key,256);return toBase64Url(bits)}
export function defaultAccessConfig(){return{team1:{name:"Apey's Apes",salt:"",passwordHash:"",passwordVersion:0,iterations:PBKDF2_ITERATIONS},team2:{name:"The Harambe Hunters",salt:"",passwordHash:"",passwordVersion:0,iterations:PBKDF2_ITERATIONS},updatedAt:new Date().toISOString()}}
export async function getAccessConfig(env){const raw=await env.DROPS_KV.get(ACCESS_KEY);if(!raw)return defaultAccessConfig();try{const parsed=JSON.parse(raw);const base=defaultAccessConfig();const normaliseTeam=key=>({...base[key],...(parsed[key]||{}),name:clamp(parsed[key]?.name||base[key].name,80),passwordVersion:Math.max(0,Number.parseInt(parsed[key]?.passwordVersion??0,10)||0),iterations:Math.min(PBKDF2_MAX_ITERATIONS,Math.max(1,Number.parseInt(parsed[key]?.iterations??PBKDF2_ITERATIONS,10)||PBKDF2_ITERATIONS))});return{team1:normaliseTeam("team1"),team2:normaliseTeam("team2"),updatedAt:parsed.updatedAt||base.updatedAt}}catch{return defaultAccessConfig()}}
export async function saveAccessConfig(env,config){config.updatedAt=new Date().toISOString();await env.DROPS_KV.put(ACCESS_KEY,JSON.stringify(config))}
export async function setTeamPassword(config,team,password){if(!["team1","team2"].includes(team))throw new Error("Invalid team.");const cleanPassword=String(password||"");if(!cleanPassword)return;if(cleanPassword.length<10)throw new Error("Team passwords must be at least 10 characters.");if(cleanPassword.length>128)throw new Error("Team passwords cannot exceed 128 characters.");const salt=toBase64Url(crypto.getRandomValues(new Uint8Array(24)));config[team].salt=salt;config[team].iterations=PBKDF2_ITERATIONS;config[team].passwordHash=await hashPassword(cleanPassword,salt,PBKDF2_ITERATIONS);config[team].passwordVersion=(Number(config[team].passwordVersion)||0)+1}
export async function verifyTeamPassword(config,team,password){const entry=config?.[team];if(!entry?.salt||!entry?.passwordHash)return false;const actual=await hashPassword(String(password||""),entry.salt,entry.iterations||PBKDF2_ITERATIONS);return constantTimeEqual(actual,entry.passwordHash)}
export async function createTeamAccessCookie(team,env,config){const payload=btoa(JSON.stringify({team,version:Number(config?.[team]?.passwordVersion||0),exp:Date.now()+ACCESS_TTL_SECONDS*1000}));const signature=await hmac(payload,env.SESSION_SECRET);return`${ACCESS_COOKIE}=${encodeURIComponent(`${payload}.${signature}`)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${ACCESS_TTL_SECONDS}`}
export function clearTeamAccessCookie(){return`${ACCESS_COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`}
export async function getTeamAccess(request,env){const raw=getCookie(request,ACCESS_COOKIE);const[payload,signature]=raw.split(".");if(!payload||!signature)return null;try{const expected=await hmac(payload,env.SESSION_SECRET);if(!constantTimeEqual(signature,expected))return null;const data=JSON.parse(atob(payload));if(!["team1","team2"].includes(data.team)||Number(data.exp)<Date.now())return null;const config=await getAccessConfig(env);if(!config[data.team]?.passwordHash)return null;if(Number(data.version)!==Number(config[data.team].passwordVersion))return null;return data.team}catch{return null}}
function clientAddress(request){return clamp(request.headers.get("CF-Connecting-IP")||request.headers.get("X-Forwarded-For")?.split(",")[0]||"unknown",80)}
function loginRateKey(request,team){return`bingo:team-login-rate:${team}:${clientAddress(request)}`}
export async function checkLoginRateLimit(request,env,team){const key=loginRateKey(request,team);const raw=await env.DROPS_KV.get(key);const attempts=Math.max(0,Number.parseInt(raw||"0",10)||0);return{allowed:attempts<LOGIN_MAX_ATTEMPTS,key}}
export async function recordFailedLogin(env,key){const raw=await env.DROPS_KV.get(key);const attempts=Math.max(0,Number.parseInt(raw||"0",10)||0)+1;await env.DROPS_KV.put(key,String(attempts),{expirationTtl:LOGIN_WINDOW_SECONDS})}
export async function clearFailedLogins(env,key){await env.DROPS_KV.delete(key)}
export function boardKeyForAccessTeam(team){return team==="team2"?"ash":team==="team1"?"ember":null}
