import { hybridKv } from "../../_hybridKv.js";

const WOM_BASE="https://api.wiseoldman.net/v2", WOM_GROUP_ID="12095", STALE_TTL=7*24*60*60;
const DEFAULT_CLUE_WEIGHTS={beginner:.5,easy:1,medium:2,hard:4,elite:7,master:10};
const CLUE_METRICS={beginner:"clue_scrolls_beginner",easy:"clue_scrolls_easy",medium:"clue_scrolls_medium",hard:"clue_scrolls_hard",elite:"clue_scrolls_elite",master:"clue_scrolls_master"};
const norm=v=>String(v||"").trim().toLowerCase().replace(/[ _-]+/g," ");
const rsnOf=p=>String(p?.rsn||p?.name||"").trim();
function gainedValue(entry,metric){const data=entry?.data||entry?.gains||entry||{};if(Array.isArray(data)){const row=data.find(x=>String(x?.metric||"")===metric);return Math.max(0,Number(row?.gained??row?.score?.gained??row?.values?.gained)||0);}for(const bucket of [data?.activities,data?.bosses,data?.skills,data]){const v=bucket?.[metric];if(typeof v==="number")return Math.max(0,v);if(v&&typeof v==="object"){for(const x of [v.gained,v.score?.gained,v.value?.gained,v.experience?.gained])if(typeof x==="number")return Math.max(0,x);}}return 0;}
async function womBulkOnce(startIso,endIso,env){const qs=new URLSearchParams({startDate:startIso,endDate:endIso}),headers={Accept:"application/json"};if(env?.WOM_API_KEY)headers["x-api-key"]=env.WOM_API_KEY;const r=await fetch(`${WOM_BASE}/groups/${WOM_GROUP_ID}/bulk-gained?${qs}`,{headers});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null;}catch{}if(!r.ok)throw new Error(`Wise Old Man returned ${r.status}${body?.message?`: ${body.message}`:""}`);const rows=Array.isArray(body)?body:body?.data;if(!Array.isArray(rows))throw new Error("Wise Old Man returned an unexpected progress response.");return rows;}
async function womBulk(startIso,endIso,env){let last;for(let i=0;i<3;i++){try{return await womBulkOnce(startIso,endIso,env);}catch(e){last=e;if(i<2)await new Promise(r=>setTimeout(r,250*(i+1)));}}throw last;}
async function bulkWithFallback(state,week,challenge,env){const start=new Date(challenge.opensAt||week.startDate||0),close=new Date(challenge.closesAt||week.endDate||Date.now()),end=new Date(Math.min(Date.now(),Number.isFinite(close.getTime())?close.getTime():Date.now()));if(!Number.isFinite(start.getTime()))throw new Error("Challenge start time is invalid.");const kv=hybridKv(env,"drops"),key=`ironkin-games:auto-score:${week.id}:${challenge.id}`;try{const rows=await womBulk(start.toISOString(),end.toISOString(),env);if(kv)await kv.put(key,JSON.stringify({rows,updatedAt:new Date().toISOString()}),{expirationTtl:STALE_TTL});return{rows,stale:false};}catch(error){if(kv){try{const raw=await kv.get(key);if(raw){const cached=JSON.parse(raw);if(Array.isArray(cached.rows))return{rows:cached.rows,stale:true,warning:"WOM is temporarily unavailable; preview uses the last successful tracking snapshot."};}}catch{}}throw error;}}
function roster(team,state){const out=[...(team.members||[])],cid=String(team.captainDiscordId||"");if(cid&&!out.some(p=>String(p.discordId||p.id||"")===cid)){const c=(state.signups||[]).find(p=>String(p.discordId||p.id||"")===cid);if(c)out.unshift(c);}return out.filter(p=>rsnOf(p));}
function rankRows(rows,challenge,state){const direction=challenge?.scoring?.ranking==="lowest"?1:-1;rows.sort((a,b)=>direction*(a.score-b.score)||tieCompare(a,b,challenge));let place=0,lastKey=null;rows.forEach((r,i)=>{const key=scoreKey(r,challenge);if(key!==lastKey)place=i+1;r.placement=place;lastKey=key;const scale=state.scoring?.[challenge.kind==="side"?"side":"main"]||[];r.points=Number(scale[r.placement-1])||0;});return rows;}
function scoreKey(r,c){if(c?.scoring?.mode==="weighted-clues")return [r.score,...(c.scoring.tieBreak||["master","elite","hard","medium","easy","beginner"]).map(k=>r.breakdown?.[k]||0)].join("|");return String(r.score);}
function tieCompare(a,b,c){if(c?.scoring?.mode==="weighted-clues"){for(const k of c.scoring.tieBreak||["master","elite","hard","medium","easy","beginner"]){const d=(b.breakdown?.[k]||0)-(a.breakdown?.[k]||0);if(d)return d;}}return String(a.teamName).localeCompare(String(b.teamName));}
export async function calculateAutomaticChallenge(state,week,challenge,env){const tracker=String(challenge.trackerType||"");if(String(challenge.trackingMethod||"")!=="automatic")return null;
 if(tracker==="timed-wom-attempt"||tracker==="boss-rush"){const rows=(state.teams||[]).map(team=>{const attempts=(state.sessions||[]).filter(s=>s.type==="boss-rush"&&String(s.weekId)===String(week.id)&&String(s.challengeId)===String(challenge.id)&&String(s.teamId)===String(team.id)&&s.status==="completed");const bosses=new Set();attempts.forEach(a=>(a.completedBosses||Object.keys(a.bossGains||{})).forEach(b=>bosses.add(b)));const expected=roster(team,state).length*Math.max(1,Number(challenge.attemptsPerPlayer)||1);return{teamId:team.id,teamName:team.name,score:bosses.size,scoreLabel:`${bosses.size} unique bosses`,breakdown:{attemptsCompleted:attempts.length,attemptsExpected:expected,uniqueBosses:[...bosses].sort()}};});return{tracker,rows:rankRows(rows,challenge,state),stale:false};}
 const bulk=await bulkWithFallback(state,week,challenge,env),byName=new Map(bulk.rows.map(x=>[norm(x?.player?.displayName||x?.player?.username||x?.username),x]));
 if(tracker==="wom-clues"||tracker==="clue-progress"){const weights={...DEFAULT_CLUE_WEIGHTS,...(challenge.scoring?.weights||{})};const rows=(state.teams||[]).map(team=>{const breakdown={beginner:0,easy:0,medium:0,hard:0,elite:0,master:0};for(const p of roster(team,state)){const entry=byName.get(norm(rsnOf(p)));for(const [k,m] of Object.entries(CLUE_METRICS))breakdown[k]+=Math.floor(gainedValue(entry,m));}const score=Object.entries(breakdown).reduce((n,[k,v])=>n+v*(Number(weights[k])||0),0);return{teamId:team.id,teamName:team.name,score,scoreLabel:`${score} weighted clue points`,breakdown};});return{tracker,rows:rankRows(rows,challenge,state),stale:bulk.stale,warning:bulk.warning};}
 if(tracker==="wom-metric"){const metric=String(challenge.trackerConfig?.metric||"").trim();if(!metric)throw new Error("This WOM Metric Progress challenge does not have a metric key configured.");const rows=(state.teams||[]).map(team=>{let score=0;for(const p of roster(team,state))score+=gainedValue(byName.get(norm(rsnOf(p))),metric);return{teamId:team.id,teamName:team.name,score,scoreLabel:`${score} ${challenge.trackerConfig?.metricLabel||metric}`,breakdown:{metric}};});return{tracker,rows:rankRows(rows,challenge,state),stale:bulk.stale,warning:bulk.warning};}
 throw new Error("This automatic tracker is not supported.");}
export function automaticSubmission(week,challenge,row){return{id:`auto:${week.id}:${challenge.id}:${row.teamId}`,weekId:week.id,challengeId:challenge.id,teamId:row.teamId,submittedBy:"automatic-tracker",submittedAt:new Date().toISOString(),score:row.scoreLabel,scoreValue:row.score,proofUrl:"",notes:"Automatically calculated from the challenge tracker.",status:"approved",points:row.points,placement:row.placement,staffNote:"",source:"automatic",autoBreakdown:row.breakdown,reviewedAt:new Date().toISOString(),reviewedBy:"automatic-tracker"};}
