import { hybridKv } from "../../_hybridKv.js";
import { listClaims, refreshClaim } from "./_contracts.js";
import { shoppingEventId, shoppingSubmissionRows, shoppingTeamProgress } from "./_shoppingList.js";
import { locationHuntStops, locationRows, currentLocationRows } from "./_locationHunt.js";

const WOM_BASE="https://api.wiseoldman.net/v2", WOM_GROUP_ID="12095", STALE_TTL=7*24*60*60;
const DEFAULT_CLUE_WEIGHTS={beginner:.5,easy:1,medium:2,hard:4,elite:7,master:10};
const CLUE_METRICS={beginner:"clue_scrolls_beginner",easy:"clue_scrolls_easy",medium:"clue_scrolls_medium",hard:"clue_scrolls_hard",elite:"clue_scrolls_elite",master:"clue_scrolls_master"};
const BOSS_RUSH_BOSSES = [
["abyssal_sire","Abyssal Sire"],["alchemical_hydra","Alchemical Hydra"],["amoxliatl","Amoxliatl"],["araxxor","Araxxor"],["artio","Artio"],["barrows_chests","Barrows Chests"],["brutus","Brutus"],["bryophyta","Bryophyta"],["callisto","Callisto"],["calvarion","Calvar'ion"],["cerberus","Cerberus"],["chambers_of_xeric","Chambers of Xeric"],["chambers_of_xeric_challenge_mode","Chambers of Xeric (CM)"],["chaos_elemental","Chaos Elemental"],["chaos_fanatic","Chaos Fanatic"],["commander_zilyana","Commander Zilyana"],["corporeal_beast","Corporeal Beast"],["crazy_archaeologist","Crazy Archaeologist"],["dagannoth_prime","Dagannoth Prime"],["dagannoth_rex","Dagannoth Rex"],["dagannoth_supreme","Dagannoth Supreme"],["deranged_archaeologist","Deranged Archaeologist"],["doom_of_mokhaiotl","Doom of Mokhaiotl"],["duke_sucellus","Duke Sucellus"],["general_graardor","General Graardor"],["giant_mole","Giant Mole"],["grotesque_guardians","Grotesque Guardians"],["hespori","Hespori"],["kalphite_queen","Kalphite Queen"],["king_black_dragon","King Black Dragon"],["kraken","Kraken"],["kreearra","Kree'Arra"],["kril_tsutsaroth","K'ril Tsutsaroth"],["lunar_chests","Lunar Chests"],["mad_angel","Mad Angel"],["maggot_king","Maggot King"],["mimic","Mimic"],["nex","Nex"],["nightmare","Nightmare"],["phosanis_nightmare","Phosani's Nightmare"],["obor","Obor"],["phantom_muspah","Phantom Muspah"],["sarachnis","Sarachnis"],["scorpia","Scorpia"],["scurrius","Scurrius"],["shellbane_gryphon","Shellbane Gryphon"],["skotizo","Skotizo"],["sol_heredit","Sol Heredit"],["spindel","Spindel"],["tempoross","Tempoross"],["the_gauntlet","The Gauntlet"],["the_corrupted_gauntlet","The Corrupted Gauntlet"],["the_hueycoatl","The Hueycoatl"],["the_leviathan","The Leviathan"],["the_royal_titans","The Royal Titans"],["the_whisperer","The Whisperer"],["theatre_of_blood","Theatre of Blood"],["theatre_of_blood_hard_mode","Theatre of Blood (HM)"],["thermonuclear_smoke_devil","Thermonuclear Smoke Devil"],["tombs_of_amascut","Tombs of Amascut"],["tombs_of_amascut_expert","Tombs of Amascut (Expert Mode)"],["tzkal_zuk","TzKal-Zuk"],["tztok_jad","TzTok-Jad"],["vardorvis","Vardorvis"],["venenatis","Venenatis"],["vetion","Vet'ion"],["vorkath","Vorkath"],["wintertodt","Wintertodt"],["yama","Yama"],["zalcano","Zalcano"],["zulrah","Zulrah"]
];
const norm=v=>String(v||"").trim().toLowerCase().replace(/[ _-]+/g," ");
const rsnOf=p=>String(p?.rsn||p?.name||"").trim();
function gainedValue(entry,metric){const data=entry?.data||entry?.gains||entry||{};if(Array.isArray(data)){const row=data.find(x=>String(x?.metric||"")===metric);return Math.max(0,Number(row?.gained??row?.score?.gained??row?.values?.gained)||0);}for(const bucket of [data?.activities,data?.bosses,data?.skills,data]){const v=bucket?.[metric];if(typeof v==="number")return Math.max(0,v);if(v&&typeof v==="object"){for(const x of [v.gained,v.score?.gained,v.value?.gained,v.experience?.gained])if(typeof x==="number")return Math.max(0,x);}}return 0;}
async function womBulkOnce(startIso,endIso,env){const qs=new URLSearchParams({startDate:startIso,endDate:endIso}),headers={Accept:"application/json"};if(env?.WOM_API_KEY)headers["x-api-key"]=env.WOM_API_KEY;const r=await fetch(`${WOM_BASE}/groups/${WOM_GROUP_ID}/bulk-gained?${qs}`,{headers});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null;}catch{}if(!r.ok)throw new Error(`Wise Old Man returned ${r.status}${body?.message?`: ${body.message}`:""}`);const rows=Array.isArray(body)?body:body?.data;if(!Array.isArray(rows))throw new Error("Wise Old Man returned an unexpected progress response.");return rows;}
async function womBulk(startIso,endIso,env){let last;for(let i=0;i<3;i++){try{return await womBulkOnce(startIso,endIso,env);}catch(e){last=e;if(i<2)await new Promise(r=>setTimeout(r,250*(i+1)));}}throw last;}
async function bulkWithFallback(state,week,challenge,env){const start=new Date(challenge.opensAt||week.startDate||0),close=new Date(challenge.closesAt||week.endDate||Date.now()),end=new Date(Math.min(Date.now(),Number.isFinite(close.getTime())?close.getTime():Date.now()));if(!Number.isFinite(start.getTime()))throw new Error("Challenge start time is invalid.");const kv=hybridKv(env,"drops"),key=`ironkin-games:auto-score:${week.id}:${challenge.id}`;try{const rows=await womBulk(start.toISOString(),end.toISOString(),env);if(kv)await kv.put(key,JSON.stringify({rows,updatedAt:new Date().toISOString()}),{expirationTtl:STALE_TTL});return{rows,stale:false};}catch(error){if(kv){try{const raw=await kv.get(key);if(raw){const cached=JSON.parse(raw);if(Array.isArray(cached.rows))return{rows:cached.rows,stale:true,warning:"WOM is temporarily unavailable; preview uses the last successful tracking snapshot."};}}catch{}}throw error;}}
function roster(team,state){const out=[...(team.members||[])],cid=String(team.captainDiscordId||"");if(cid&&!out.some(p=>String(p.discordId||p.id||"")===cid)){const c=(state.signups||[]).find(p=>String(p.discordId||p.id||"")===cid);if(c)out.unshift(c);}return out.filter(p=>rsnOf(p));}
function rankRows(rows,challenge,state){const direction=challenge?.scoring?.ranking==="lowest"?1:-1;rows.sort((a,b)=>direction*(a.score-b.score)||tieCompare(a,b,challenge));let place=0,lastKey=null;rows.forEach((r,i)=>{const key=scoreKey(r,challenge);if(key!==lastKey)place=i+1;r.placement=place;lastKey=key;const scale=state.scoring?.[challenge.kind==="side"?"side":"main"]||[];r.points=Number(scale[r.placement-1])||0;});return rows;}
function scoreKey(r,c){if(c?.scoring?.mode==="weighted-clues")return [r.score,...(c.scoring.tieBreak||["master","elite","hard","medium","easy","beginner"]).map(k=>r.breakdown?.[k]||0)].join("|");return String(r.score);}
function tieCompare(a,b,c){if(c?.scoring?.mode==="weighted-clues"){for(const k of c.scoring.tieBreak||["master","elite","hard","medium","easy","beginner"]){const d=(b.breakdown?.[k]||0)-(a.breakdown?.[k]||0);if(d)return d;}}return String(a.teamName).localeCompare(String(b.teamName));}
export async function calculateAutomaticChallenge(state,week,challenge,env){const tracker=String(challenge.trackerType||"");if(String(challenge.trackingMethod||"")!=="automatic")return null;
 if(tracker==="location-hunt"){const rows=[];for(const team of state.teams||[]){const stops=locationHuntStops(challenge,week),latest=currentLocationRows(await locationRows(env,week.id,challenge.id,team.id)),approved=stops.map(s=>({stop:s,row:latest.get(s.id)})).filter(x=>x.row?.status==="approved"),elapsed=approved.reduce((n,x)=>n+Math.max(0,new Date(x.row.submitted_at).getTime()-new Date(x.stop.revealsAt).getTime()),0);rows.push({teamId:team.id,teamName:team.name,score:approved.length,elapsedMs:elapsed,scoreLabel:`${approved.length} / ${stops.length} locations`,breakdown:{approved:approved.length,total:stops.length,elapsedMs:elapsed,locations:approved.map(x=>({title:x.stop.title,submittedAt:x.row.submitted_at,revealsAt:x.stop.revealsAt,proofUrl:x.row.proof_url}))}});}rows.sort((a,b)=>b.score-a.score||a.elapsedMs-b.elapsedMs||String(a.teamName).localeCompare(String(b.teamName)));let place=0,last="";rows.forEach((r,i)=>{const key=`${r.score}|${r.elapsedMs}`;if(key!==last)place=i+1;r.placement=place;r.points=Number((state.scoring?.side||[])[place-1])||0;last=key;});return{tracker,rows,stale:false};}
 if(tracker==="shopping-list"){const rows=[];for(const team of state.teams||[]){const eventId=shoppingEventId(week.id,challenge.id,team.id),allRows=await shoppingSubmissionRows(env,eventId),progress=shoppingTeamProgress(state,team,challenge,allRows),found=progress.filter(x=>x.status==="approved");rows.push({teamId:team.id,teamName:team.name,score:found.length,scoreLabel:`${found.length} / ${progress.length} shopping list items`,breakdown:{found:found.length,total:progress.length,items:found.map(x=>({itemId:x.itemId,name:x.name,player:x.playerName,obtainedAt:x.obtainedAt}))}});}return{tracker,rows:rankRows(rows,challenge,state),stale:false};}
 if(tracker==="contracts"){const rows=[];for(const team of state.teams||[]){let claims=await listClaims(env,week.id,challenge.id,team.id);const refreshed=[];for(const claim of claims){try{refreshed.push(await refreshClaim(env,claim,true));}catch{refreshed.push(claim);}}const score=refreshed.filter(c=>c.completed).reduce((n,c)=>n+(Number(c.points)||0),0);rows.push({teamId:team.id,teamName:team.name,score,scoreLabel:`${score} contract points`,breakdown:{claimed:refreshed.length,completed:refreshed.filter(c=>c.completed).length,contracts:refreshed.map(c=>({name:c.contract_name,tier:c.tier,points:c.points,completed:c.completed,progress:c.progress,target:c.target,player:c.player_name}))}});}return{tracker,rows:rankRows(rows,challenge,state),stale:false};}
 if(tracker==="timed-wom-attempt"||tracker==="boss-rush"){
  // A Boss Rush attempt is finished once an ending submission exists. Late finishes are
  // still completed attempts (they may require staff review), so do not drop them from
  // the public 8/8 completion count simply because their status is `late_review`.
  const allFinished=(state.sessions||[]).filter(s=>s.type==="boss-rush"&&String(s.weekId)===String(week.id)&&String(s.challengeId)===String(challenge.id)&&(s.status==="completed"||s.status==="late_review"||!!s.completedAt));
  const rows=(state.teams||[]).map(team=>{const currentRoster=roster(team,state),discordIds=new Set(currentRoster.map(p=>String(p?.discordId||p?.id||"")).filter(Boolean)),rsns=new Set(currentRoster.map(p=>norm(rsnOf(p))).filter(Boolean));const attempts=allFinished.filter(s=>{const playerDiscordId=String(s.playerDiscordId||s.discordId||"");const playerRsn=norm(s.rsn||s.playerName||"");const identityMatches=(playerDiscordId&&discordIds.has(playerDiscordId))||(playerRsn&&rsns.has(playerRsn));if(identityMatches)return true;const hasUsableIdentity=!!playerDiscordId||!!playerRsn;return !hasUsableIdentity&&String(s.teamId)===String(team.id);});const bosses=new Set();attempts.forEach(a=>(a.completedBosses||Object.keys(a.bossGains||{})).forEach(b=>bosses.add(b)));const expected=currentRoster.length*Math.max(1,Number(challenge.attemptsPerPlayer)||1),counted=new Set([...bosses].filter(metric=>BOSS_RUSH_BOSSES.some(([key])=>key===metric))),missedBosses=BOSS_RUSH_BOSSES.filter(([metric])=>!counted.has(metric)).map(([metric,label])=>({metric,label}));return{teamId:team.id,teamName:team.name,score:counted.size,scoreLabel:`${counted.size} / ${BOSS_RUSH_BOSSES.length} unique bosses`,breakdown:{attemptsCompleted:Math.min(attempts.length,expected||attempts.length),attemptsExpected:expected,totalBosses:BOSS_RUSH_BOSSES.length,uniqueBosses:[...counted].sort(),missedBosses}};});return{tracker,rows:rankRows(rows,challenge,state),stale:false};}
 const bulk=await bulkWithFallback(state,week,challenge,env),byName=new Map(bulk.rows.map(x=>[norm(x?.player?.displayName||x?.player?.username||x?.username),x]));
 if(tracker==="wom-clues"||tracker==="clue-progress"){const weights={...DEFAULT_CLUE_WEIGHTS,...(challenge.scoring?.weights||{})};const rows=(state.teams||[]).map(team=>{const breakdown={beginner:0,easy:0,medium:0,hard:0,elite:0,master:0};for(const p of roster(team,state)){const entry=byName.get(norm(rsnOf(p)));for(const [k,m] of Object.entries(CLUE_METRICS))breakdown[k]+=Math.floor(gainedValue(entry,m));}const score=Object.entries(breakdown).reduce((n,[k,v])=>n+v*(Number(weights[k])||0),0);return{teamId:team.id,teamName:team.name,score,scoreLabel:`${score} weighted clue points`,breakdown};});return{tracker,rows:rankRows(rows,challenge,state),stale:bulk.stale,warning:bulk.warning};}
 if(tracker==="wom-metric"){const metric=String(challenge.trackerConfig?.metric||"").trim();if(!metric)throw new Error("This WOM Metric Progress challenge does not have a metric key configured.");const rows=(state.teams||[]).map(team=>{let score=0;for(const p of roster(team,state))score+=gainedValue(byName.get(norm(rsnOf(p))),metric);return{teamId:team.id,teamName:team.name,score,scoreLabel:`${score} ${challenge.trackerConfig?.metricLabel||metric}`,breakdown:{metric}};});return{tracker,rows:rankRows(rows,challenge,state),stale:bulk.stale,warning:bulk.warning};}
 throw new Error("This automatic tracker is not supported.");}
export function automaticSubmission(week,challenge,row){return{id:`auto:${week.id}:${challenge.id}:${row.teamId}`,weekId:week.id,challengeId:challenge.id,teamId:row.teamId,submittedBy:"automatic-tracker",submittedAt:new Date().toISOString(),score:row.scoreLabel,scoreValue:row.score,proofUrl:"",notes:"Automatically calculated from the challenge tracker.",status:"approved",points:row.points,placement:row.placement,staffNote:"",source:"automatic",autoBreakdown:row.breakdown,reviewedAt:new Date().toISOString(),reviewedBy:"automatic-tracker"};}
