import { supabaseRest, isUniqueViolation } from "../_supabase.js";
import { womFetch } from "../../_wom.js";

export const CONTRACT_TIERS={safe:{label:"Safe",points:3,slots:2},risky:{label:"Risky",points:7,slots:4},"all-in":{label:"All-In",points:15,slots:2}};
export const CONTRACT_REFRESH_MS=10*60*1000;
const num=v=>Math.max(0,Number(v)||0);
export function cleanContracts(list){return (Array.isArray(list)?list:[]).map((c,i)=>({id:String(c.id||`contract-${i+1}`),name:String(c.name||`Contract ${i+1}`),tier:CONTRACT_TIERS[c.tier]?c.tier:"safe",metric:String(c.metric||"").trim(),metricLabel:String(c.metricLabel||c.metric||"").trim(),target:Math.max(1,Number(c.target)||1)})).filter(c=>c.metric);}
function snapshotFrom(data){return data?.latestSnapshot||data?.player?.latestSnapshot||data?.snapshot||null;}
export function metricValue(snapshot,metric){const d=snapshot?.data||snapshot||{};for(const bucket of [d.skills,d.bosses,d.activities]){const row=bucket?.[metric];if(typeof row==="number")return num(row);if(row&&typeof row==="object"){for(const key of ["experience","kills","score","value"]){if(row[key]!==undefined)return num(row[key]);}}}return 0;}
export async function updateAndReadMetric(env,rsn,metric,{requireFresh=false}={}){const name=String(rsn||"").trim();if(!name)throw new Error("Your roster profile does not have an RSN assigned.");const requestedAt=Date.now();let data={};try{const r=await womFetch(env,`/players/${encodeURIComponent(name)}`,{method:"POST"},"Ironkin Games Contracts");const text=await r.text();try{data=text?JSON.parse(text):{};}catch{}if(!r.ok)throw new Error(data?.message||data?.error||`WOM returned ${r.status}`);}catch(e){throw new Error(`Could not update Wise Old Man: ${e.message}`);}let snap=snapshotFrom(data);const fresh=s=>{const t=new Date(s?.createdAt||s?.updatedAt||0).getTime();return Number.isFinite(t)&&t>=requestedAt-5000;};if(!snap||(requireFresh&&!fresh(snap))){for(let i=0;i<6;i++){if(i)await new Promise(r=>setTimeout(r,550));const r=await womFetch(env,`/players/${encodeURIComponent(name)}`,{},"Ironkin Games Contracts");if(!r.ok)continue;const d=await r.json().catch(()=>({}));const candidate=snapshotFrom(d);if(candidate&&(!requireFresh||fresh(candidate))){snap=candidate;break;}}}if(!snap)throw new Error("Wise Old Man did not return a player snapshot.");if(requireFresh&&!fresh(snap))throw new Error("WOM has not confirmed a fresh baseline yet. Please try again in a moment.");return{value:metricValue(snap,metric),snapshotAt:snap.createdAt||snap.updatedAt||new Date().toISOString()};}
export async function listClaims(env,weekId,challengeId,teamId,testMode=false){const r=await supabaseRest(env,`ironkin_games_contract_claims?week_id=eq.${encodeURIComponent(weekId)}&challenge_id=eq.${encodeURIComponent(challengeId)}&team_id=eq.${encodeURIComponent(teamId)}&is_test=eq.${testMode?"true":"false"}&select=*&order=claimed_at.asc`);return await r.json();}
export async function insertClaim(env,row){try{const r=await supabaseRest(env,"ironkin_games_contract_claims",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify([row])});return (await r.json())?.[0]||null;}catch(e){if(isUniqueViolation(e))throw Object.assign(new Error("That contract was just claimed, or you already have a contract."),{status:409});throw e;}}
export async function refreshClaim(env,claim,force=false){const last=new Date(claim.last_refreshed_at||claim.claimed_at||0).getTime();if(!force&&Number.isFinite(last)&&Date.now()-last<CONTRACT_REFRESH_MS)return claim;const snap=await updateAndReadMetric(env,claim.rsn,claim.metric);const progress=Math.max(0,snap.value-num(claim.baseline)),completed=Boolean(claim.completed)||progress>=num(claim.target),now=new Date().toISOString();const patch={current_value:snap.value,progress,completed,last_refreshed_at:now,updated_at:now,...(completed&&!claim.completed?{completed_at:now}:{})};const r=await supabaseRest(env,`ironkin_games_contract_claims?id=eq.${encodeURIComponent(claim.id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(patch)});const saved=(await r.json())?.[0]||{...claim,...patch};return{...saved,_wom:{snapshotAt:snap.snapshotAt,currentValue:snap.value,baseline:num(claim.baseline),progress}};}
