import { getSession, isStaffSession } from "../_auth.js";
import { loadGames, memberTeam, challengeFor } from "./_store.js";
import { memberForSession } from "./_bossRush.js";
import { CONTRACT_TIERS, CONTRACT_REFRESH_MS, cleanContracts, updateAndReadMetric, listClaims, insertClaim, refreshClaim } from "./_contracts.js";
import { supabaseRest } from "../_supabase.js";

function openNow(challenge){const now=Date.now(),a=challenge.opensAt?new Date(challenge.opensAt).getTime():null,b=challenge.closesAt?new Date(challenge.closesAt).getTime():null;return(!Number.isFinite(a)||now>=a)&&(!Number.isFinite(b)||now<=b);}
function publicClaim(c){return{id:c.id,contractId:c.contract_id,name:c.contract_name,tier:c.tier,points:Number(c.points)||0,metricLabel:c.metric_label,target:Number(c.target)||0,playerDiscordId:c.player_discord_id,playerName:c.player_name,rsn:c.rsn,progress:Number(c.progress)||0,completed:Boolean(c.completed),claimedAt:c.claimed_at,lastRefreshedAt:c.last_refreshed_at||"",completedAt:c.completed_at||""};}
function testParams(request,body={}){const u=new URL(request.url),pick=k=>String(body[k]??u.searchParams.get(k)??"");return{requested:pick("test")==="1",teamId:pick("testTeamId"),playerDiscordId:pick("testPlayerDiscordId")};}
async function resolveContext(request,env,body={}){const session=await getSession(request,env);if(!session)return{error:Response.json({error:"Sign in with Discord first."},{status:401})};const state=await loadGames(env),staff=isStaffSession(session),test=testParams(request,body),url=new URL(request.url);const ownTeam=memberTeam(state,session);let team=ownTeam,player=team?memberForSession(team,session):null,testMode=false;const adminTeamId=staff?String(body.adminTeamId??url.searchParams.get("adminTeamId")??""):"";if(adminTeamId){team=(state.teams||[]).find(t=>String(t.id)===adminTeamId)||team;player=ownTeam&&String(ownTeam.id)===String(team?.id)?memberForSession(team,session):null;}if(!team&&staff){team=(state.teams||[])[0]||null;player=null;}if(test.requested){if(!staff)return{error:Response.json({error:"Staff test mode only."},{status:403})};team=(state.teams||[]).find(t=>String(t.id)===test.teamId)||null;if(!team)return{error:Response.json({error:"Choose a valid test team."},{status:400})};player=(team.members||[]).find(m=>String(m.discordId||m.id||"")===test.playerDiscordId)||null;if(!player)return{error:Response.json({error:"Choose a rostered player on that test team."},{status:400})};testMode=true;}const{week,challenge}=challengeFor(state,body.weekId||url.searchParams.get("weekId"),body.challengeId||url.searchParams.get("challengeId"));if(!team)return{error:Response.json({error:"You are not assigned to an Ironkin Games team."},{status:403})};if(!week||!challenge||challenge.trackerType!=="contracts")return{error:Response.json({error:"Contracts challenge not found."},{status:404})};return{session,state,team,week,challenge,player,testMode,ownTeam,actorDiscordId:testMode?String(player.discordId||player.id||""):String(session.id)};}
export async function onRequestGet({request,env,waitUntil}){
 const ctx=await resolveContext(request,env,{});if(ctx.error)return ctx.error;
 const contracts=cleanContracts(ctx.challenge.contracts),storedClaims=await listClaims(env,ctx.week.id,ctx.challenge.id,ctx.team.id,ctx.testMode),staff=isStaffSession(ctx.session);
 // Page loads are read-only and fast: never block the UI on WOM. Stored progress is returned immediately.
 // Stale claims are refreshed in the background at most once per CONTRACT_REFRESH_MS.
 const refreshDiagnostics=storedClaims.map(claim=>({ok:true,queued:false,rsn:String(claim.rsn||claim.player_name||"Player"),metric:String(claim.metric||""),baseline:Number(claim.baseline)||0,currentValue:Number(claim.current_value)||0,progress:Number(claim.progress)||0,lastRefreshedAt:claim.last_refreshed_at||""}));
 const stale=storedClaims.filter(claim=>{const last=new Date(claim.last_refreshed_at||claim.claimed_at||0).getTime();return !Number.isFinite(last)||Date.now()-last>=CONTRACT_REFRESH_MS;});
 stale.forEach((claim,i)=>{const diag=refreshDiagnostics.find(x=>x.rsn===String(claim.rsn||claim.player_name||"Player")&&x.metric===String(claim.metric||""));if(diag)diag.queued=true;});
 if(stale.length&&typeof waitUntil==="function"){
   waitUntil((async()=>{for(const claim of stale){try{await refreshClaim(env,claim,false);}catch(e){} await new Promise(r=>setTimeout(r,1100));}})());
 }
 return Response.json({contracts,claims:storedClaims.map(publicClaim),refreshDiagnostics,backgroundRefreshQueued:stale.length,tiers:CONTRACT_TIERS,isOpen:ctx.testMode||openNow(ctx.challenge),myDiscordId:ctx.actorDiscordId,isStaff:staff,testMode:ctx.testMode,teamId:String(ctx.team.id||""),teamName:String(ctx.team.name||"Team"),teams:staff?(ctx.state.teams||[]).map(t=>({id:String(t.id||""),name:String(t.name||"Team")})).filter(t=>t.id):[],canClaim:Boolean(ctx.player)&&(ctx.testMode||String(ctx.ownTeam?.id||"")===String(ctx.team.id||""))},{headers:{"Cache-Control":"no-store"}});
}
export async function onRequestPost({request,env}){const body=await request.json().catch(()=>({})),ctx=await resolveContext(request,env,body);if(ctx.error)return ctx.error;const action=String(body.action||"claim"),staff=isStaffSession(ctx.session);if(action==="reset"){if(!staff)return Response.json({error:"Staff only."},{status:403});if(!body.claimId)return Response.json({error:"Claim is required."},{status:400});await supabaseRest(env,`ironkin_games_contract_claims?id=eq.${encodeURIComponent(body.claimId)}&is_test=eq.${ctx.testMode?"true":"false"}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});return Response.json({ok:true});}
 if(action==="reset-test"){if(!staff||!ctx.testMode)return Response.json({error:"Staff test mode only."},{status:403});await supabaseRest(env,`ironkin_games_contract_claims?week_id=eq.${encodeURIComponent(ctx.week.id)}&challenge_id=eq.${encodeURIComponent(ctx.challenge.id)}&team_id=eq.${encodeURIComponent(ctx.team.id)}&is_test=eq.true`,{method:"DELETE",headers:{Prefer:"return=minimal"}});return Response.json({ok:true});}
 if(action==="refresh"){const claims=await listClaims(env,ctx.week.id,ctx.challenge.id,ctx.team.id,ctx.testMode),mine=claims.find(c=>String(c.player_discord_id)===ctx.actorDiscordId);if(!mine)return Response.json({error:"Claim a contract first."},{status:409});try{return Response.json({ok:true,claim:publicClaim(await refreshClaim(env,mine,true))});}catch(e){return Response.json({error:e.message},{status:502});}}
 if(action==="admin-refresh"){if(!staff)return Response.json({error:"Staff only."},{status:403});const claims=await listClaims(env,ctx.week.id,ctx.challenge.id,ctx.team.id,ctx.testMode),claim=claims.find(c=>String(c.id)===String(body.claimId||""));if(!claim)return Response.json({error:"Contract claim not found."},{status:404});try{return Response.json({ok:true,claim:publicClaim(await refreshClaim(env,claim,true,true))});}catch(e){return Response.json({error:e.message},{status:502});}}
 if(action!=="claim")return Response.json({error:"Unknown action."},{status:400});if(!ctx.testMode&&!openNow(ctx.challenge))return Response.json({error:"Contracts are not available outside the challenge window."},{status:409});if(!ctx.player)return Response.json({error:"The selected roster profile does not have an RSN assigned."},{status:409});const contract=cleanContracts(ctx.challenge.contracts).find(c=>c.id===String(body.contractId||""));if(!contract)return Response.json({error:"Contract not found."},{status:404});const claims=await listClaims(env,ctx.week.id,ctx.challenge.id,ctx.team.id,ctx.testMode);if(claims.some(c=>String(c.player_discord_id)===ctx.actorDiscordId))return Response.json({error:"This player has already claimed a contract."},{status:409});if(claims.some(c=>String(c.contract_id)===contract.id))return Response.json({error:"That contract has already been claimed by this team."},{status:409});const tier=CONTRACT_TIERS[contract.tier],tierCount=claims.filter(c=>c.tier===contract.tier).length;if(tierCount>=tier.slots)return Response.json({error:`Your team already filled all ${tier.label} contract slots.`},{status:409});let snap;try{snap=await updateAndReadMetric(env,ctx.player.rsn||ctx.player.name,contract.metric,{requireFresh:true});}catch(e){return Response.json({error:`Baseline not captured. ${e.message}`},{status:502});}const now=new Date().toISOString();try{const row=await insertClaim(env,{week_id:ctx.week.id,challenge_id:ctx.challenge.id,team_id:ctx.team.id,contract_id:contract.id,contract_name:contract.name,tier:contract.tier,points:tier.points,metric:contract.metric,metric_label:contract.metricLabel,target:contract.target,player_discord_id:ctx.actorDiscordId,player_name:ctx.player.name||ctx.player.rsn||"Player",rsn:ctx.player.rsn||ctx.player.name,baseline:snap.value,current_value:snap.value,progress:0,completed:false,is_test:ctx.testMode,claimed_at:now,baseline_snapshot_at:snap.snapshotAt,last_refreshed_at:now,updated_at:now});return Response.json({ok:true,claim:publicClaim(row)});}catch(e){return Response.json({error:e.message},{status:e.status||500});}}
