import { getSession, isGamesAdminSession } from '../_auth.js';
import { loadGames, memberTeam } from './_store.js';
import { hybridKv } from '../../_hybridKv.js';
import { getSupabaseKey } from '../_supabase.js';
const headers={'Cache-Control':'no-store'};
const activities=['Corrupted Gauntlet','Zulrah','Vorkath','Phantom Muspah','Hallowed Sepulchre','Prifddinas Agility Course','Tempoross','Werewolf Agility Course'];
const raids=['Chambers of Xeric','Theatre of Blood','Tombs of Amascut'];
const error=(message,status=400)=>Response.json({error:message},{status,headers});
function locate(state,wid,cid,staff,test){const week=(state.weeks||[]).find(w=>String(w.id)===String(wid));let challenge=week?.challenges?.find(c=>String(c.id)===String(cid)&&(/time.trials/i.test(String(c.trackerType||''))||/ironkin time trials/i.test(String(c.name||''))));if(!challenge&&staff&&test&&cid==='staff-preview-time-trials'&&state.weeks?.[2]?.id===week?.id)challenge={id:cid,name:'Ironkin Time Trials',revealed:false};return {week,challenge};}
const store=(env,weekId,challengeId,test)=>hybridKv(env,'drops');
const key=(w,c,test)=>`ironkin-games:time-trials:v1:${test?'test':'live'}:${w}:${c}`;
async function read(env,w,c,test){try{const x=await store(env,w,c,test).get(key(w,c,test));const rows=JSON.parse(x||'[]');return Array.isArray(rows)?rows:[];}catch{return [];}}
async function save(env,w,c,test,rows){await store(env,w,c,test).put(key(w,c,test),JSON.stringify(rows));}
function teamFor(state,session,staff,test,requested){let team=memberTeam(state,session);if(staff&&test&&requested)team=state.teams.find(t=>String(t.id)===String(requested))||team;return team;}
function score(state,rows){const approved=rows.filter(r=>r.status==='approved');const result=activities.map((name,index)=>{const best=[];for(const t of state.teams||[]){const mine=approved.filter(r=>r.kind==='activity'&&r.index===index&&r.teamId===t.id).sort((a,b)=>index===6?b.value-a.value:a.value-b.value)[0];if(mine)best.push({...mine,teamName:t.name});}best.sort((a,b)=>index===6?b.value-a.value:a.value-b.value);return {name,results:best.map((r,i)=>({teamId:r.teamId,teamName:r.teamName,player:r.player,value:r.value,rank:i+1,points:[10,7,4,1][i]||0}))};});const raidResults=raids.map((name,index)=>({name,teams:(state.teams||[]).map(t=>{const r=approved.find(x=>x.kind==='raid'&&x.index===index&&x.teamId===t.id);return r?{teamId:t.id,teamName:t.name,player:r.player}:null;}).filter(Boolean)}));const standings=(state.teams||[]).map(t=>{const placements=result.map(a=>a.results.find(x=>x.teamId===t.id)?.points||0).sort((a,b)=>b-a);const trials=placements.slice(0,5).reduce((a,b)=>a+b,0);const count=raidResults.filter(r=>r.teams.some(x=>x.teamId===t.id)).length;const bonus=count*2+(count===3?4:0);return {teamId:t.id,teamName:t.name,trials,bonus,total:trials+bonus};}).sort((a,b)=>b.total-a.total||b.trials-a.trials||a.teamName.localeCompare(b.teamName));return {activities:result,raids:raidResults,standings};}
function ctx(state,session,weekId,challengeId,test,requested){const staff=isGamesAdminSession(session),{week,challenge}=locate(state,weekId,challengeId,staff,test);if(!week||!challenge)return {error:error('Time Trials is not assigned to this week.',404)};if(!staff&&!challenge.revealed)return {error:error('This challenge has not been revealed.',403)};const team=teamFor(state,session,staff,test,requested);if(!team&&!staff)return {error:error('You must be rostered on a team.',403)};const end=new Date(challenge.closesAt||week.endDate||0).getTime();const start=new Date(challenge.opensAt||week.startDate||0).getTime();return {staff,team,week,challenge,isClosed:!test&&Number.isFinite(end)&&Date.now()>end,isOpen:test||Number.isFinite(start)&&Date.now()>=start};}
export async function onRequestGet({request,env}){const session=await getSession(request,env);if(!session)return error('Sign in required.',401);const state=await loadGames(env),u=new URL(request.url),w=u.searchParams.get('weekId'),c=u.searchParams.get('challengeId'),test=isGamesAdminSession(session)&&u.searchParams.get('test')==='1';const x=ctx(state,session,w,c,test,u.searchParams.get('testTeamId'));if(x.error)return x.error;const rows=await read(env,w,c,test),scored=score(state,rows);return Response.json({...scored,isStaff:x.staff,teamId:x.team?.id||'',testMode:test,isClosed:x.isClosed,submissions:rows.filter(r=>r.teamId===x.team?.id).map(r=>({...r,teamName:undefined})).reverse(),reviewQueue:x.staff?rows.filter(r=>r.status==='pending').map(r=>({...r,teamName:state.teams.find(t=>t.id===r.teamId)?.name||'Team'})):[]},{headers});}
async function upload(env,file,id){const base=String(env.SUPABASE_URL||'').replace(/\/$/,''),k=getSupabaseKey(env);if(!base||!k)throw Error('Screenshot storage is not configured.');const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';const h={apikey:k,'Content-Type':file.type,'x-upsert':'false'};if(!k.startsWith('sb_secret_'))h.Authorization=`Bearer ${k}`;const path=`time-trials/${id}.${ext}`,r=await fetch(`${base}/storage/v1/object/ironkin-games-proofs/${path}`,{method:'POST',headers:h,body:file});if(!r.ok)throw Error('Screenshot upload failed.');return `${base}/storage/v1/object/public/ironkin-games-proofs/${path}`;}
export async function onRequestPost({request,env}){const session=await getSession(request,env);if(!session)return error('Sign in required.',401);const f=await request.formData(),w=String(f.get('weekId')||''),c=String(f.get('challengeId')||''),test=f.get('test')==='1'&&isGamesAdminSession(session),state=await loadGames(env),x=ctx(state,session,w,c,test);if(x.error)return x.error;if(!x.team)return error('Select a team before submitting.',403);if(!x.isOpen||x.isClosed)return error('Submissions are not open.',403);const kind=String(f.get('kind')||''),index=Number(f.get('index')),player=String(f.get('player')||'').trim().slice(0,60),members=String(f.get('members')||'').trim().slice(0,240),file=f.get('proof');if(!['activity','raid'].includes(kind)||!Number.isInteger(index)||index<0||index>=(kind==='raid'?3:8))return error('Invalid activity.');if(!player)return error('Enter the player RSN.');if(kind==='raid'&&members.split(',').map(s=>s.trim()).filter(Boolean).length<2)return error('List at least two other teammates.');if(!(file instanceof File)||!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size<1||file.size>8*1024*1024)return error('Upload a PNG, JPEG or WebP screenshot under 8 MB.');let value=null;if(kind==='activity'){const input=String(f.get('result')||'').trim();if(index===6){if(!/^\d{1,8}$/.test(input))return error('Enter a whole-number personal point score.');value=Number(input);}else{const m=input.match(/^(?:(\d{1,3}):)?(\d{1,2})(?:\.(\d{1,3}))?$/);if(!m)return error('Enter a time as MM:SS.ss.');value=(Number(m[1]||0)*60+Number(m[2]))*1000+Number((m[3]||'').padEnd(3,'0'));if(Number(m[2])>=60||value<=0)return error('Invalid completion time.');}if(!Number.isSafeInteger(value)||value<=0)return error('Invalid result.');}const id=crypto.randomUUID();let proofUrl;try{proofUrl=await upload(env,file,id);}catch(e){return error(e.message,503);}const rows=await read(env,w,c,test),now=new Date().toISOString();rows.push({id,kind,index,name:(kind==='raid'?raids:activities)[index],teamId:x.team.id,player,members:kind==='raid'?members:'',value,proofUrl,status:'pending',note:'',submittedBy:String(session.id),submittedAt:now});await save(env,w,c,test,rows);return Response.json({ok:true,id,status:'pending'},{headers});}
export async function onRequestPatch({request,env}){const session=await getSession(request,env);if(!session||!isGamesAdminSession(session))return error('Staff access required.',403);const b=await request.json().catch(()=>({})),w=String(b.weekId||''),c=String(b.challengeId||''),test=Boolean(b.test),state=await loadGames(env),x=ctx(state,session,w,c,test);if(x.error)return x.error;if(!['approved','rejected'].includes(b.status))return error('Invalid review status.');if(b.status==='rejected'&&!String(b.note||'').trim())return error('A rejection reason is required.');const rows=await read(env,w,c,test),row=rows.find(r=>r.id===b.id);if(!row||row.status!=='pending')return error('Pending submission not found.',404);row.status=b.status;row.note=String(b.note||'').slice(0,500);row.reviewedAt=new Date().toISOString();row.reviewedBy=String(session.id);await save(env,w,c,test,rows);return Response.json({ok:true,standings:score(state,rows).standings},{headers});}
